<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Question Bank Export</title>
    <style>
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 11px;
            line-height: 1.6;
            color: #333;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 3px solid #4F46E5;
            padding-bottom: 15px;
        }

        .header h1 {
            color: #4F46E5;
            margin: 0;
            font-size: 24px;
        }

        .header .meta {
            color: #666;
            font-size: 10px;
            margin-top: 5px;
        }

        .question {
            margin-bottom: 25px;
            border: 1px solid #ddd;
            border-radius: 5px;
            padding: 15px;
            break-inside: avoid;
        }

        .question-header {
            display: flex;
            justify-content: space-between;
            margin-bottom: 10px;
            font-weight: bold;
        }

        .question-number {
            color: #4F46E5;
            font-size: 14px;
        }

        .badges {
            display: flex;
            gap: 5px;
        }

        .badge {
            padding: 2px 8px;
            border-radius: 3px;
            font-size: 9px;
            font-weight: bold;
        }

        .badge-type {
            background: #DBEAFE;
            color: #1E40AF;
        }

        .badge-difficulty {
            background: #FEF3C7;
            color: #92400E;
        }

        .badge-easy {
            background: #D1FAE5;
            color: #065F46;
        }

        .badge-medium {
            background: #FEF3C7;
            color: #92400E;
        }

        .badge-hard {
            background: #FEE2E2;
            color: #991B1B;
        }

        .question-text {
            font-size: 12px;
            margin-bottom: 10px;
            font-weight: 500;
        }

        .options {
            margin-left: 20px;
        }

        .option {
            margin-bottom: 5px;
            padding: 5px;
            background: #f9f9f9;
            border-radius: 3px;
        }

        .option.correct {
            background: #D1FAE5;
            font-weight: bold;
        }

        .explanation {
            margin-top: 10px;
            padding: 10px;
            background: #EFF6FF;
            border-left: 3px solid #3B82F6;
            font-size: 10px;
        }

        .footer {
            text-align: center;
            margin-top: 30px;
            padding-top: 15px;
            border-top: 1px solid #ddd;
            font-size: 9px;
            color: #666;
        }

        .page-break {
            page-break-after: always;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>📚 Question Bank Export</h1>
        <div class="meta">
            Exported on: {{ $exported_at }} | Total Questions: {{ $total }}
        </div>
    </div>

    @foreach ($questions as $index => $question)
        <div class="question">
            <div class="question-header">
                <span class="question-number">Question #{{ $index + 1 }}</span>
                <div class="badges">
                    <span class="badge badge-type">{{ strtoupper(str_replace('_', ' ', $question->type)) }}</span>
                    <span class="badge badge-{{ $question->difficulty }}">
                        {{ strtoupper($question->difficulty) }}
                    </span>
                </div>
            </div>

            <div class="question-text">
                {{ $question->question_text }}
            </div>

            @if ($question->options && in_array($question->type, ['mcq_single', 'mcq_multiple']))
                <div class="options">
                    @foreach ($question->options as $optionIndex => $option)
                        <div class="option {{ in_array($option, $question->correct_answer ?? []) ? 'correct' : '' }}">
                            {{ chr(65 + $optionIndex) }}. {{ $option }}
                            @if (in_array($option, $question->correct_answer ?? []))
                                ✓
                            @endif
                        </div>
                    @endforeach
                </div>
            @endif

            @if ($question->explanation)
                <div class="explanation">
                    <strong>Explanation:</strong> {{ $question->explanation }}
                </div>
            @endif
        </div>

        @if (($index + 1) % 5 == 0 && $index + 1 < $questions->count())
            <div class="page-break"></div>
        @endif
    @endforeach

    <div class="footer">
        Generated by LMS Question Bank System
    </div>
</body>

</html>
