<?php

namespace Database\Factories;

use App\Models\ForumCategory;
use App\Models\ForumThread;
use App\Models\User;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Models\ForumThread>
 */
class ForumThreadFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var class-string<ForumThread>
     */
    protected $model = ForumThread::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $title = fake()->unique()->sentence(6);

        return [
            'category_id' => ForumCategory::factory(),
            'user_id' => User::factory(),
            'title' => $title,
            // slug + last_activity_at are auto-generated by the model's booted() hook
            'slug' => null,
            'content' => fake()->paragraphs(3, true),
            'is_pinned' => false,
            'is_locked' => false,
            'views_count' => 0,
            'replies_count' => 0,
            'likes_count' => 0,
            'last_activity_at' => null,
            'last_reply_user_id' => null,
        ];
    }
}
